### ISSUE TITLE
doesnt have all mods

### ISSUE THREAD

**Issue by RoninRulez** [TheMulhima/Lumafly#116]
### Explanation of the new feature

Lumafly doesn't have ALL of the mods. Like, there is a harder modded boss called Uuwuu [yes thats the name] and other stuff. If I search it up, it isnt there. soooo, yeah.

**Comment by BadMagic100** [comment]
This is by design. Lumafly and all other installers share the same list of mods, called modlinks. For any given missing mod, one (or both) of the following is probably true:
* The author of the mod has chosen not to list it on modlinks 
* There is no port available for the current patch of hollow knight (this might be true for uuwuu, iirc it is old)
